### ISSUE TITLE
DismRebootRequiredException is thrown for non-exceptional cases

### ISSUE THREAD

**Issue by jhennessey** [jeffkl/ManagedDism#109]
When enabling a feature (or trying to perform other operations) succeeds, but requires a reboot, a DismRebootRequiredException is thrown. Even if the consumer catches that exception, subsequent calls fail with the same exception. 

Would a change to this behavior be considered?

**Comment by jeffkl** [comment]
This managed API is a slim wrapper around the native APIs.  When a `DismRebootRequiredException` is thrown, its because a native API returned `ERROR_SUCCESS_REBOOT_REQUIRED`.

For example, when you call `DismApi.DismAddPackage()`, its just calling the native [DismAddPackage function](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dismaddpackage-function) for you and marshalling the data between the managed and native world.  The `DismAddPackage` function can return all kinds of HRESULT values depending on what happened, one of which is `ERROR_SUCCESS_REBOOT_REQUIRED`.  I'm not sure if there's anything we can do in this wrapper, as what you're asking for seems to be a change to the native API which I don't have any control over unfortunately.

Or are you asking for something different?

**Comment by jhennessey** [comment]
Thanks for the explanation!

My first thought would be to just not have this wrapper throw for `ERROR_SUCCESS_*` HRESULTs as the requested action completed successfully (albeit with some additional context). It appears that `ERROR_SUCCESS_REBOOT_REQUIRED` is the only special `ERROR_SUCCESS_*` result that falls into this category. In my case, I'm calling `EnableFeature` and the feature gets enabled as expected but obviously the underlying DISM API indicates a reboot is required to finish the job. However, since many of the wrapped calls check for the same return values it becomes very difficult to make subsequent calls (you have to `try...catch` for the reboot exception a lot). I should note that my primary use case is to enable several features and roll them up into one reboot (this works from the dism.exe command line).

My suggestion above would obviously be a breaking change for those catching reboot exceptions today. So, it would likely have to be an opt-in behavior. There are probably other alternatives as well.

Some of the relevant areas of the code:
https://github.com/jeffkl/ManagedDism/blob/d06a513209c85e6547fe6fed49371d170953de04/src/Microsoft.Dism/DismApi.EnableFeature.cs#L184
https://github.com/jeffkl/ManagedDism/blob/d06a513209c85e6547fe6fed49371d170953de04/src/Microsoft.Dism/DismUtilities.cs#L319
https://github.com/jeffkl/ManagedDism/blob/d06a513209c85e6547fe6fed49371d170953de04/src/Microsoft.Dism/DismException.cs#L81

**Comment by jeffkl** [comment]
Sounds reasonable, maybe there should be a static property that you could set like:
```c#
// Disable throwing an exception when DISMAPI requires a reboot
DismApi.ThrowExceptionOnRebootRequired = false;
```
Then the code would check that and not throw for `ERROR_SUCCESS_REBOOT_REQUIRED`.  But how would you as a caller like to be notified that a reboot is required? The existing method doesn't return anything...

**Comment by jhennessey** [comment]
> But how would you as a caller like to be notified that a reboot is required? The existing method doesn't return anything...

Good question :). I took a stab at an approach that tacked a property onto the `DismSession` object:
https://github.com/jhennessey/ManagedDism/commit/37ea4ae75aa93e0980b24fbd477ae55b82a9a59e

Would that be a viable approach?

**Comment by jeffkl** [comment]
Yeah that looks really good.  Here's what I think we should do in order to keep this API still a wrapper but also expose some new functionality.

1. Make a new file DismApi.OpenSessionEx.cs, we'll make it be just like OpenSession
  https://github.com/jeffkl/ManagedDism/blob/master/src/Microsoft.Dism/DismApi.OpenSession.cs
2. Add a new class, `DismSessionOptions` with this new property that callers can set like you have
  ```C#
public sealed class DismSessionOptions
{
    /// <summary>
    /// Gets or sets a value indicating whether an exception should be thrown when an action requires a reboot.
    /// </summary>
    public bool ThrowExceptionOnRebootRequired { get; set; } = true;
}
```
3. Add new "Ex" methods for all of the public methods in `DismApi.OpenSession.cs`
  ```c#
public static DismSession OpenOfflineSessionEx(string imagePath, DismSessionOptions options = null);
public static DismSession OpenOfflineSessionEx(string imagePath, string windowsDirectory, string systemDrive, DismSessionOptions options = null);
public static DismSession OpenOnlineSessionEx(DismSessionOptions options = null);
```
4. Add to the constructor of `DismSession` to accept these options and add a property to the session if a reboot is required even if someone catches the exception.  Don't expose the options that were set since they may or may not have called the Ex method.

So very similar to your idea, just keeping it all in the session and placing the functionality in the Ex side of things to keep the main API pure.

What do you think?

**Comment by jhennessey** [comment]
Sounds good. 

I actually went down a similar route with a `DismSessionOptions` class at first but then didn't want to change the existing classes too much...adding the Ex class addresses that.

**Comment by jeffkl** [comment]
Do you want to send a PR or do you want me to do it?  Contributions are always welcome!

**Comment by jhennessey** [comment]
I will throw together a PR :)
